name: Build Pre-Release

on:
  push:                      # 任何 push，都触发
  workflow_dispatch:         # 支持手动触发

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: "Set up JDK 21"
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: gradle
      - name: "Build with Gradle"
        run: |
          ./gradlew clean
          ./gradlew shadowJar -PBuildFull=false
          ./gradlew shadowJar -PBuildFull=true
      - name: "Stage"
        run: |
          mkdir -p staging
          mv build/libs/*.jar staging/
      - name: "Build & test"
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "done!"
      - name: "GitHub Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.TAG }}"
          prerelease: true
          files: |
            staging/*.jar
